### ISSUE TITLE
No bundle ID set. You *must* set a bundle ID to use AwGo.

### ISSUE THREAD

**Issue by bloatfan** [nikitavoloboev/alfred-awesome-lists#15]
### Bug 🐞

env:
macOS Catalina 10.15.4
Alfred 4

### Steps to Reproduce:

1.  ./alfred-awesome-lists -l chrome

output:

```
{
  "variables": {
    "AW_SESSION_ID": "UGMM5BYHWJF9FS46R27O9OAP"
  },
  "items": [
    {
      "title": "No bundle ID set. You *must* set a bundle ID to use AwGo.",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}2020/07/06 00:15:30 Sent 1 result(s) to Alfred
2020/07/06 00:15:30 [ERROR] No bundle ID set. You *must* set a bundle ID to use AwGo.
2020/07/06 00:15:30 ---------------------- 1ms -----------------------
```

please help me, thanks!

**Comment by nikivdev** [comment]
`-l chrome` whats this flag? I don't it's supported.

**Comment by bloatfan** [comment]
> `-l chrome` whats this flag? I don't it's supported.

ok，i remove the -l flag,  execute again

step:

```
./alfred-my-mind -wiki chrome
```

output:

```
panic: invalid Workflow environment: alfred_workflow_bundleid is not set, alfred_workflow_cache is not set, alfred_workflow_data is not set

goroutine 1 [running]:
github.com/deanishe/awgo.NewFromEnv(0x0, 0x0, 0xc0000fdf10, 0x2, 0x2, 0xc000100000)
        /Users/nikivi/go/pkg/mod/github.com/deanishe/awgo@v0.22.0/workflow.go:159 +0xbe3
github.com/deanishe/awgo.New(...)
        /Users/nikivi/go/pkg/mod/github.com/deanishe/awgo@v0.22.0/workflow.go:149
main.init.0()
        /Users/nikivi/src/extensions/alfred/alfred-my-mind/main.go:21 +0xda
```

**Comment by nikivdev** [comment]
why `-wiki` flag?

<img width="586" alt="image" src="https://user-images.githubusercontent.com/6391776/86550899-eb52af00-bf43-11ea-9974-e14048d19d15.png">

This is what you should see in script filter. Just run it with: 

`./alfred-awesome-lists "$1"`

It doesn't work?

**Comment by bloatfan** [comment]
> why `-wiki` flag?
> 
> <img alt="image" width="586" src="https://user-images.githubusercontent.com/6391776/86550899-eb52af00-bf43-11ea-9974-e14048d19d15.png">
> 
> This is what you should see in script filter. Just run it with:
> 
> `./alfred-awesome-lists "$1"`
> 
> It doesn't work?

hi, i use this alfred workflow `https://github.com/nikitavoloboev/alfred-my-mind`

not `https://github.com/nikitavoloboev/alfred-awesome-lists`

but when i try `alfred-awesome-lists`, it the other error

env:

```
macOS Catalina 10.15.4
Alfred 4.1
```

![image](https://user-images.githubusercontent.com/18484770/86551286-3803ad80-bf77-11ea-9da4-8d13ce167248.png)

**Comment by nikivdev** [comment]
The error you get is because you don't run it inside Alfred. You need to set some env variables indeed.

Maybe look into 

https://github.com/deanishe/alfred-firefox/blob/master/server.sh#L14

Also why are you running it from command line? Run it from Alfred.

**Comment by bloatfan** [comment]
> The error you get is because you don't run it inside Alfred. You need to set some env variables indeed.
> 
> Maybe look into
> 
> https://github.com/deanishe/alfred-firefox/blob/master/server.sh#L14
> 
> Also why are you running it from command line? Run it from Alfred.

when i search by alfred, i show no result, so i try it from command line, maybe due to GWF in china, i will check my network ，try

thank your reply!

![Kapture 2020-07-06 at 11 25 37](https://user-images.githubusercontent.com/18484770/86552763-8155fc00-bf7b-11ea-9e76-9b210379e441.gif)

**Comment by nikivdev** [comment]
Can you check what is written in console in Alfred when you do the search?

**Comment by bloatfan** [comment]
> Can you check what is written in console in Alfred when you do the search?


debug output:


```
[13:06:18.507] Logging Started...
[13:06:26.718] Awesome lists[Script Filter] Queuing argument ''
[13:06:26.828] Awesome lists[Script Filter] Script with argv '' finished
[13:06:26.830] STDERR: Awesome lists[Script Filter] 💜
13:06:26 workflow.go:614: -------- Awesome lists/1.2 (AwGo/0.13.2) ---------
13:06:26 feedback.go:431: Sent 1 result(s) to Alfred
13:06:26 feedback.go:421: Feedback already sent. Ignoring.
13:06:26 workflow.go:790: ---------------------- 11ms ----------------------
[13:06:26.844] Awesome lists[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "8OXFIP2CMMH4NKEMPLEERDCZ"
  },
  "items": [
    {
      "title": "No matching items",
      "subtitle": "Try a different query?",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      }
    }
  ]
}
[13:06:27.150] Awesome lists[Script Filter] Queuing argument 'c'
[13:06:27.223] Awesome lists[Script Filter] Queuing argument 'ch'
[13:06:27.227] Awesome lists[Script Filter] Script with argv 'c' finished
[13:06:27.229] STDERR: Awesome lists[Script Filter] 💜
13:06:27 workflow.go:614: -------- Awesome lists/1.2 (AwGo/0.13.2) ---------
13:06:27 feedback.go:431: Sent 1 result(s) to Alfred
13:06:27 feedback.go:421: Feedback already sent. Ignoring.
13:06:27 workflow.go:790: ---------------------- 2ms -----------------------
[13:06:27.230] Awesome lists[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "8OXFIP2CMMH4NKEMPLEERDCZ"
  },
  "items": [
    {
      "title": "No matching items",
      "subtitle": "Try a different query?",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      }
    }
  ]
}
[13:06:27.303] Awesome lists[Script Filter] Script with argv 'ch' finished
[13:06:27.306] STDERR: Awesome lists[Script Filter] 💜
13:06:27 workflow.go:614: -------- Awesome lists/1.2 (AwGo/0.13.2) ---------
13:06:27 feedback.go:431: Sent 1 result(s) to Alfred
13:06:27 feedback.go:421: Feedback already sent. Ignoring.
13:06:27 workflow.go:790: ---------------------- 1ms -----------------------
[13:06:27.308] Awesome lists[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "8OXFIP2CMMH4NKEMPLEERDCZ"
  },
  "items": [
    {
      "title": "No matching items",
      "subtitle": "Try a different query?",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      }
    }
  ]
}
[13:06:27.397] Awesome lists[Script Filter] Queuing argument 'chr'
[13:06:27.410] Awesome lists[Script Filter] Script with argv 'chr' finished
[13:06:27.411] STDERR: Awesome lists[Script Filter] 💜
13:06:27 workflow.go:614: -------- Awesome lists/1.2 (AwGo/0.13.2) ---------
13:06:27 feedback.go:431: Sent 1 result(s) to Alfred
13:06:27 feedback.go:421: Feedback already sent. Ignoring.
13:06:27 workflow.go:790: ---------------------- 1ms -----------------------
[13:06:27.412] Awesome lists[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "8OXFIP2CMMH4NKEMPLEERDCZ"
  },
  "items": [
    {
      "title": "No matching items",
      "subtitle": "Try a different query?",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      }
    }
  ]
}
[13:06:27.485] Awesome lists[Script Filter] Queuing argument 'chro'
[13:06:27.498] Awesome lists[Script Filter] Script with argv 'chro' finished
[13:06:27.500] STDERR: Awesome lists[Script Filter] 💜
13:06:27 workflow.go:614: -------- Awesome lists/1.2 (AwGo/0.13.2) ---------
13:06:27 feedback.go:431: Sent 1 result(s) to Alfred
13:06:27 feedback.go:421: Feedback already sent. Ignoring.
13:06:27 workflow.go:790: ---------------------- 1ms -----------------------
[13:06:27.501] Awesome lists[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "8OXFIP2CMMH4NKEMPLEERDCZ"
  },
  "items": [
    {
      "title": "No matching items",
      "subtitle": "Try a different query?",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      }
    }
  ]
}
[13:06:27.541] Awesome lists[Script Filter] Queuing argument 'chrom'
[13:06:27.552] Awesome lists[Script Filter] Script with argv 'chrom' finished
[13:06:27.559] STDERR: Awesome lists[Script Filter] 💜
13:06:27 workflow.go:614: -------- Awesome lists/1.2 (AwGo/0.13.2) ---------
13:06:27 feedback.go:431: Sent 1 result(s) to Alfred
13:06:27 feedback.go:421: Feedback already sent. Ignoring.
13:06:27 workflow.go:790: ---------------------- 1ms -----------------------
[13:06:27.560] Awesome lists[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "8OXFIP2CMMH4NKEMPLEERDCZ"
  },
  "items": [
    {
      "title": "No matching items",
      "subtitle": "Try a different query?",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      }
    }
  ]
}
[13:06:27.614] Awesome lists[Script Filter] Queuing argument 'chrome'
[13:06:27.688] Awesome lists[Script Filter] Script with argv 'chrome' finished
[13:06:27.698] STDERR: Awesome lists[Script Filter] 💜
13:06:27 workflow.go:614: -------- Awesome lists/1.2 (AwGo/0.13.2) ---------
13:06:27 feedback.go:431: Sent 1 result(s) to Alfred
13:06:27 feedback.go:421: Feedback already sent. Ignoring.
13:06:27 workflow.go:790: ---------------------- 1ms -----------------------
[13:06:27.699] Awesome lists[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "8OXFIP2CMMH4NKEMPLEERDCZ"
  },
  "items": [
    {
      "title": "No matching items",
      "subtitle": "Try a different query?",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      }
    }
  ]
}
```

**Comment by nikivdev** [comment]
strange, no idea why it happens

**Comment by bloatfan** [comment]
> strange, no idea why it happens

i know this reason, this url `https://raw.githubusercontent.com/sindresorhus/awesome/main/readme.md` is forbided due to `GWF` exist in china

![image](https://user-images.githubusercontent.com/18484770/86560763-b0776800-bf91-11ea-8921-2b1593b1ddb3.png)


**eventually， i try by http proxy，it's ok, thank your reply!**

```
http_proxy='http://127.0.0.1:7890' https_proxy='http://127.0.0.1:7890' alfred_workflow_bundleid="nikivi.awesome.lists" alfred_workflow_version="1.2" alfred_workflow_name="Awesome lists" alfred_workflow_cache="/tmp" alfred_workflow_data="/tmp" ./alfred-awesome-lists chrome
```

the output:

```
🍺
14:08:33 -------- Awesome lists/1.2 (AwGo/0.20.2) ---------
14:08:33 no cached releases
14:08:33 no downloads available
14:08:33 query=
{
  "variables": {
    "AW_SESSION_ID": "DLBFYOGEKY8X06NZ0CNLXCYM"
  },
  "items": [
    {
      "title": "Chrome DevTools",
      "arg": "https://github.com/ChromeDevTools/awesome-chrome-devtools#readme",
      "uid": "Chrome DevTools",
      "valid": true
    }
  ]
}14:08:35 Sent 1 result(s) to Alfred
14:08:35 ------------------ 1.955585714s ------------------
```
